name: localstorage
description: LocalStorage for Flutter. Alternative to React Native's AsyncStorage.
version: 5.0.0
homepage: https://github.com/lesnitsky/flutter_localstorage

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
